<!DOCTYPE html>

@php $locale = App()->currentLocale(); @endphp

<html lang="{{$locale == 'en' ? 'English' : ($locale == 'ar' ? 'العربية' : 'Français')}}" dir="{{$locale == 'ar' ? 'rtl' : 'ltr'}}">


 <head>

   @include('layouts.partials.head')

   @stack('css')
 </head>

 <body class="{{ Auth::check() && Auth::user()->profile && Auth::user()->profile->theme ? Auth::user()->profile->theme : 'default'}}">

    @include('layouts.partials.nav')

        <!-- Start Welcome area -->
    <div class="all-content-wrapper {{$locale == 'ar' ? 'all-content-wrapper-rtl' : ''}}">
        @include('layouts.partials.header')

        @yield('content')

        @include('layouts.partials.footer')
    </div>


    <div id="loadingDiv" class="spinner-border text-success" role="status"
        style="width: 100%; height: 100%;position: absolute">
        <div class="inner" style="width: 200px; height: 200px;text-align:center"><svg xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                style="margin: auto; display: block; /*! shape-rendering: auto; */" width="200px" height="200px"
                viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                <g transform="translate(50,50)">
                    <circle cx="0" cy="0" r="10" fill="none" stroke="#d74946" stroke-width="4"
                        stroke-dasharray="31.41592653589793 31.41592653589793">
                        <animateTransform attributeName="transform" type="rotate" values="0 0 0;360 0 0" times="0;1"
                            dur="0.48076923076923084s" calcMode="spline" keySplines="0.2 0 0.8 1" begin="0"
                            repeatCount="indefinite"></animateTransform>
                    </circle>
                    <circle cx="0" cy="0" r="20" fill="none" stroke="#0069ce" stroke-width="4"
                        stroke-dasharray="62.83185307179586 62.83185307179586">
                        <animateTransform attributeName="transform" type="rotate" values="0 0 0;360 0 0" times="0;1"
                            dur="0.48076923076923084s" calcMode="spline" keySplines="0.2 0 0.8 1"
                            begin="-0.12019230769230771" repeatCount="indefinite"></animateTransform>
                    </circle>
                    <circle cx="0" cy="0" r="30" fill="none" stroke="#f0af31" stroke-width="4"
                        stroke-dasharray="94.24777960769379 94.24777960769379">
                        <animateTransform attributeName="transform" type="rotate" values="0 0 0;360 0 0" times="0;1"
                            dur="0.48076923076923084s" calcMode="spline" keySplines="0.2 0 0.8 1"
                            begin="-0.24038461538461542" repeatCount="indefinite"></animateTransform>
                    </circle>
                    <circle cx="0" cy="0" r="40" fill="none" stroke="#94b224" stroke-width="4"
                        stroke-dasharray="125.66370614359172 125.66370614359172">
                        <animateTransform attributeName="transform" type="rotate" values="0 0 0;360 0 0" times="0;1"
                            dur="0.48076923076923084s" calcMode="spline" keySplines="0.2 0 0.8 1"
                            begin="-0.36057692307692313" repeatCount="indefinite"></animateTransform>
                    </circle>
                </g>
                <!-- [ldio] generated by https://loading.io/ -->
            </svg>
            <span class="sr-only">{{ __('Loading...') }}</span>
        </div>
    </div>

    @include('layouts.partials.footer-scripts')

    @stack('js')
 </body>

</html>
